# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitall < Formula
  desc ""
  homepage "https://github.com/jkassis/homebrew-tap"
  version "0.5.18"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jkassis/gitall/releases/download/v0.5.18/gitall_0.5.18_darwin_amd64.tar.gz"
      sha256 "5548227fd9d484cfdcf6250bc426ba43bef65b6d0a6c90f6e203a46b5c920b29"

      def install
        bin.install "gitall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jkassis/gitall/releases/download/v0.5.18/gitall_0.5.18_darwin_arm64.tar.gz"
      sha256 "4aa2c9840c06cc2ebe12b7867cd338dca4fa4f64c9543dab53568382a9b07dbe"

      def install
        bin.install "gitall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jkassis/gitall/releases/download/v0.5.18/gitall_0.5.18_linux_arm64.tar.gz"
      sha256 "b7071416be56bb1694be38ddb401e2d3367fa0a935b1adeb362d68d09b7e2837"

      def install
        bin.install "gitall"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jkassis/gitall/releases/download/v0.5.18/gitall_0.5.18_linux_amd64.tar.gz"
      sha256 "8dbf42e08e4e80a1260571963d258264d3a17bdc2b410e774b18d1bad6569e77"

      def install
        bin.install "gitall"
      end
    end
  end
end
